language: csharp
solution: Evolution/Evolution.sln

before_install:
  - sudo pip install codecov

install:
  - nuget restore Evolution/Evolution.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Debug Evolution/Evolution.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Evolution/Evolution.Test/bin/Debug/Evolution.Test.dll
  
after_success:
  - codecov
