language: csharp
solution: Evolution/Evolution.sln

before_install:
  - sudo -H pip install codecov

install:
  - nuget restore Evolution/Evolution.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Debug Evolution/Evolution.sln
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./Evolution/Evolution.Test/bin/Debug/Evolution.Test.dll
  - mono ./Evolution/packages/OpenCover.4.6.166/tools/OpenCover.Console.exe -register:user -target:"./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe" -targetargs:"Evolution/Evolution.Test/bin/Debug/Evolution.Test.dll" -filter:"+[Evolution*]*" -output:coverage.xml

after_success:
  - codecov
