language: csharp
solution: Evolution/Evolution.sln
install:
  - nuget restore Evolution/Evolution.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Evolution/Evolution.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Evolution/Evolution.Test/bin/Release/Evolution.Test.dll
