language: csharp
solution: Evolution/Evolution.sln

before_install:
  - sudo pip install --user codecov

install:
  - nuget restore Evolution/Evolution.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Debug Evolution/Evolution.sln
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./Evolution/Evolution.Test/bin/Debug/Evolution.Test.dll
  
after_success:
  - codecov
