using System;
using System.Collections.Generic;
using System.Linq;
using Singular.Evolution.Core;

namespace Singular.Evolution.Alterers
{
    /// <summary>
    /// Base class for crossovers. Does the basic validations on input parents
    /// Child classes call it's constructor passing their input requirements
    /// </summary>
    /// <typeparam name="G">Genotype</typeparam>
    /// <typeparam name="R">Gene</typeparam>
    /// <typeparam name="F">Fitness</typeparam>
    /// <seealso cref="Singular.Evolution.Core.IAlterer{G, F}" />
    public abstract class CrossoverBase<G, R, F> : IAlterer<G, F> where G : IListGenotype<G, R>
        where F : IComparable<F>
        where R : IGene, new()
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CrossoverBase{G, R, F}"/> class. Is for use of the inherited classes.
        /// </summary>
        /// <param name="numberOfParentsNeeded">The number of parents needed.</param>
        /// <param name="numberOfChildsGenerated">The number of childs generated.</param>
        /// <param name="minimumGenesRequired">The minimum genes required.</param>
        /// <param name="sameLengthParentsNeeded">if set to <c>true</c> [same length parents needed].</param>
        public CrossoverBase(int numberOfParentsNeeded, int numberOfChildsGenerated, int minimumGenesRequired,
            bool sameLengthParentsNeeded)
        {
            NumberOfParentsNeeded = numberOfParentsNeeded;
            NumberOfChildsGenerated = numberOfChildsGenerated;
            SameLengthParentsNeeded = sameLengthParentsNeeded;
            MinimumGenesRequired = minimumGenesRequired;
        }

        /// <summary>
        /// Gets the number of parents needed for the crossover.
        /// </summary>
        /// <value>
        /// The number of parents needed.
        /// </value>
        public int NumberOfParentsNeeded { get; }

        /// <summary>
        /// Gets a value indicating whether parents of the same length are needed for the crossover.
        /// </summary>
        /// <value>
        /// <c>true</c> if [same length parents needed]; otherwise, <c>false</c>.
        /// </value>
        public bool SameLengthParentsNeeded { get; }

        /// <summary>
        /// Gets the number of childs generated by the crossover.
        /// </summary>
        /// <value>
        /// The number of childs generated.
        /// </value>
        public int NumberOfChildsGenerated { get; }

        /// <summary>
        /// Gets the minimum parent's gene count required by the crossover.
        /// </summary>
        /// <value>
        /// The minimum genes required.
        /// </value>
        public int MinimumGenesRequired { get; }

        /// <summary>
        /// Applies the crossover on the parents.
        /// Is used to perform some basic validation before the implemented virtual method <see cref="GetOffspring"/> is called
        /// </summary>
        /// <param name="parents">The parents.</param>
        /// <returns></returns>
        /// <exception cref="System.ArgumentException">
        /// Parents should have same length
        /// or
        /// </exception>
        public IList<Individual<G, F>> Apply(IList<Individual<G, F>> parents)
        {
            if (parents.Count() != NumberOfParentsNeeded)
                throw new ArgumentException($"Input expected {NumberOfParentsNeeded} parents");


            int count = parents[0].Genotype.Count;

            foreach (Individual<G, F> individual in parents)
            {
                if (SameLengthParentsNeeded && parents.Any(p => p.Genotype.Count != count))
                    throw new ArgumentException("Parents should have same length");

                if (MinimumGenesRequired > individual.Genotype.Count)
                    throw new ArgumentException($"Parents should have at least {MinimumGenesRequired} genes");
            }

            return Individual<G, F>.FromGenotypes(GetOffspring(parents.Select(g => g.Genotype)));
        }

        /// <summary>
        /// Gets the offspring.
        /// This method is called by CrossoverBase's Apply after a successful validation
        /// </summary>
        /// <param name="parents">The parents.</param>
        /// <returns></returns>
        protected abstract IList<G> GetOffspring(IEnumerable<G> parents);
    }
}