using System.Collections.Generic;
using System.Linq;

namespace Singular.Evolution.Utils
{
    /// <summary>
    /// Extension methods for randomly taking values from lists and enumerables
    /// </summary>
    public static class RandomChooser
    {
        /// <summary>
        /// Returns an infinite enumerable where elements where randomly chosen from a list
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="list">The list.</param>
        /// <returns></returns>
        public static IEnumerable<T> ToRandomEnumerable<T>(this IList<T> list)
        {
            RandomGenerator rnd = RandomGenerator.GetInstance();
            while (true)
            {
                yield return list[rnd.NextInt(list.Count)];
            }
        }

        /// <summary>
        /// Returns am enumerable of n randomly chosen elements from a list
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="list">The list.</param>
        /// <param name="n">The n.</param>
        /// <returns></returns>
        /// <remarks>The items may repeat</remarks>
        public static IEnumerable<T> RandomTake<T>(this IList<T> list, int n)
        {
            return list.ToRandomEnumerable().Take(n);
        }

        /// <summary>
        /// Returns an enumerable generated by randomly sorting another finite enumerable
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="source">The source.</param>
        /// <returns></returns>
        /// <remarks>The source is expected to be finite</remarks>
        public static IEnumerable<T> RandomSort<T>(this IEnumerable<T> source)
        {
            List<T> destination = new List<T>();
            foreach (T item in source)
            {
                int rnd = RandomGenerator.GetInstance().NextInt(0, destination.Count + 1);
                if (rnd == destination.Count)
                {
                    destination.Add(item);
                }
                else
                {
                    destination.Add(destination[rnd]);
                    destination[rnd] = item;
                }
            }
            return destination;
        }
    }
}